name: native-tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install TCL
        run: sudo apt-get install -y tcl-tls

      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Cache Maven
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Fast build and install JedisMock
        run: mvn -B install -Dmaven.javadoc.skip -DskipTests -Dspotbugs.skip=true -Dcheckstyle.skip=true

      - name: Evaluate current JedisMock version
        run: |
          echo jm_version=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout ) >> $GITHUB_ENV 
          cat $GITHUB_ENV

      - name: Build jm-test-server
        run: mvn -B verify -Djedismock.version=${{ env.jm_version }}
        working-directory: native_tests/jm-test-server

      - name: Run jm-test-server in background
        run: java -jar target/jm-test-server-1.0-SNAPSHOT-jar-with-dependencies.jar &
        working-directory: native_tests/jm-test-server

      - name: Prepare TCL test run
        run: |
          sudo chmod +x ./gen-test-certs.sh
          sudo chmod +x ./runtest
          ./gen-test-certs.sh
        working-directory: native_tests/linux

      - name: Run native tests
        run: |
          ./runtest --host 127.0.0.1 --port 39807 --single unit/type/hash
          ./runtest --host 127.0.0.1 --port 39807 --single unit/type/list-2
        working-directory: native_tests/linux
